### ISSUE TITLE
When i try to deploy Qexo on vercel,I get error like Command "./migrate.sh" exited with 1

### ISSUE THREAD

**Issue by yinlinghunjiang** [Qexo/Qexo#138]
### Qexo 版本

v1.6.2

### 问题描述

**When i try to deploy Qexo on vercel,I get error : Command "./migrate.sh" exited with 1**

These are trace data:
[19:30:11.163] Cloning github.com/yinlinghunjiang/Qexo (Branch: main, Commit: 66cbd90)
[19:30:11.573] Cloning completed: 409.384ms
[19:30:11.633] Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[19:30:11.974] Installing build runtime...
[19:30:13.615] Build runtime installed: 1.641s
[19:30:13.646] Installing build runtime...
[19:30:15.942] Build runtime installed: 2.296s
[19:30:16.768] Looking up build cache...
[19:30:17.070] Build Cache not found
[19:30:17.697] Collecting asgiref==3.4.1
[19:30:17.712]   Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
[19:30:17.740] Collecting autopep8==1.5.7
[19:30:17.745]   Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
[19:30:17.758]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 KB 3.6 MB/s eta 0:00:00
[19:30:17.787] Collecting beautifulsoup4==4.10.0
[19:30:17.791]   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
[19:30:17.798]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 18.9 MB/s eta 0:00:00
[19:30:17.832] Collecting boto==2.49.0
[19:30:17.836]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[19:30:18.295] Collecting boto3==1.20.23
[19:30:18.300]   Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
[19:30:18.308]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 KB 22.7 MB/s eta 0:00:00
[19:30:18.873] Collecting botocore==1.23.23
[19:30:18.879]   Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
[19:30:18.960]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 107.1 MB/s eta 0:00:00
[19:30:19.019] Collecting certifi==2021.5.30
[19:30:19.029]   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
[19:30:19.037]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 27.9 MB/s eta 0:00:00
[19:30:19.246] Collecting cffi==1.15.0
[19:30:19.255]   Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
[19:30:19.267]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 KB 52.0 MB/s eta 0:00:00
[19:30:19.302] Collecting charset-normalizer==2.0.4
[19:30:19.307]   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
[19:30:19.350] Collecting click==8.0.1
[19:30:19.356]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[19:30:19.363]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 18.1 MB/s eta 0:00:00
[19:30:19.394] Collecting colorama==0.4.4
[19:30:19.400]   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
[19:30:19.429] Collecting Deprecated==1.2.13
[19:30:19.434]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[19:30:19.454] Collecting dj-database-url==0.5.0
[19:30:19.457]   Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
[19:30:19.572] Collecting Django==3.0.5
[19:30:19.581]   Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
[19:30:19.665]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 92.3 MB/s eta 0:00:00
[19:30:19.741] Collecting djongo==1.3.6
[19:30:19.746]   Downloading djongo-1.3.6.tar.gz (331 kB)
[19:30:19.755]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 KB 49.0 MB/s eta 0:00:00
[19:30:19.780]   Preparing metadata (setup.py): started
[19:30:19.959]   Preparing metadata (setup.py): finished with status 'done'
[19:30:19.994] Collecting django-cors-headers==3.10.1
[19:30:19.998]   Downloading django_cors_headers-3.10.1-py3-none-any.whl (12 kB)
[19:30:20.020] Collecting dnspython==1.16.0
[19:30:20.028]   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
[19:30:20.037]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 KB 32.5 MB/s eta 0:00:00
[19:30:20.068] Collecting gunicorn==20.1.0
[19:30:20.072]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[19:30:20.078]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 19.2 MB/s eta 0:00:00
[19:30:20.098] Collecting idna==3.2
[19:30:20.101]   Downloading idna-3.2-py3-none-any.whl (59 kB)
[19:30:20.133]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 KB 1.7 MB/s eta 0:00:00
[19:30:20.151] Collecting jmespath==0.10.0
[19:30:20.154]   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
[19:30:20.180] Collecting prettytable==2.2.0
[19:30:20.202]   Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
[19:30:20.251]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[19:30:20.257]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 17.8 MB/s eta 0:00:00
[19:30:20.278] Collecting pycodestyle==2.7.0
[19:30:20.281]   Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
[19:30:20.288]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 7.7 MB/s eta 0:00:00
[19:30:20.303] Collecting pycparser==2.21
[19:30:20.307]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[19:30:20.314]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 23.8 MB/s eta 0:00:00
[19:30:20.344] Collecting PyGithub==1.55
[19:30:20.356]   Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
[19:30:20.367]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 KB 37.3 MB/s eta 0:00:00
[19:30:20.398] Collecting PyJWT==2.3.0
[19:30:20.402]   Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
[19:30:20.854] Collecting pymongo==3.12.0
[19:30:20.862]   Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
[19:30:20.874]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 KB 55.9 MB/s eta 0:00:00
[19:30:20.917] Collecting PyNaCl==1.4.0
[19:30:20.927]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[19:30:20.942]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 KB 78.6 MB/s eta 0:00:00
[19:30:20.969] Collecting python-dateutil==2.8.2
[19:30:20.973]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[19:30:20.981]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 39.3 MB/s eta 0:00:00
[19:30:20.998] Collecting python-decouple==3.4
[19:30:21.002]   Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
[19:30:21.084] Collecting pytz==2021.1
[19:30:21.091]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[19:30:21.103]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 KB 57.3 MB/s eta 0:00:00
[19:30:21.159] Collecting requests==2.26.0
[19:30:21.163]   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
[19:30:21.170]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 13.2 MB/s eta 0:00:00
[19:30:21.195] Collecting rsa==4.7.2
[19:30:21.198]   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
[19:30:21.225] Collecting s3transfer==0.5.0
[19:30:21.228]   Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
[19:30:21.235]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 KB 16.7 MB/s eta 0:00:00
[19:30:21.257] Collecting six==1.16.0
[19:30:21.261]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[19:30:21.293] Collecting soupsieve==2.2.1
[19:30:21.297]   Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
[19:30:21.321] Collecting sqlparse==0.2.4
[19:30:21.326]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[19:30:21.343] Collecting tcping==0.1.1rc1
[19:30:21.346]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[19:30:21.352]   Preparing metadata (setup.py): started
[19:30:21.529]   Preparing metadata (setup.py): finished with status 'done'
[19:30:21.550] Collecting toml==0.10.2
[19:30:21.554]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[19:30:21.638] Collecting ujson==4.1.0
[19:30:21.643]   Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
[19:30:21.652]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 KB 30.9 MB/s eta 0:00:00
[19:30:21.665] Collecting Unipath==1.1
[19:30:21.670]   Downloading Unipath-1.1.tar.gz (30 kB)
[19:30:21.678]   Preparing metadata (setup.py): started
[19:30:21.855]   Preparing metadata (setup.py): finished with status 'done'
[19:30:21.902] Collecting urllib3==1.26.7
[19:30:21.907]   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
[19:30:21.916]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 KB 23.1 MB/s eta 0:00:00
[19:30:21.934] Collecting wcwidth==0.2.5
[19:30:21.938]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[19:30:21.968] Collecting whitenoise==5.3.0
[19:30:21.972]   Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
[19:30:22.092] Collecting wrapt==1.13.3
[19:30:22.096]   Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
[19:30:22.103]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 KB 18.3 MB/s eta 0:00:00
[19:30:22.130] Collecting Markdown==3.3.6
[19:30:22.133]   Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
[19:30:22.140]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 20.9 MB/s eta 0:00:00
[19:30:22.159] Collecting onepush==1.1.1
[19:30:22.167]   Downloading onepush-1.1.1-py3-none-any.whl (13 kB)
[19:30:22.489] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[19:30:22.972] Collecting importlib-metadata>=4.4
[19:30:22.976]   Downloading importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
[19:30:23.050] Collecting zipp>=0.5
[19:30:23.054]   Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
[19:30:23.118] Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
[19:30:23.119] Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
[19:30:23.119] Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
[19:30:23.336] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, dj-database-url, certifi, boto, zipp, wrapt, whitenoise, urllib3, ujson, toml, soupsieve, six, rsa, pymongo, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, gunicorn, dnspython, colorama, click, charset-normalizer, asgiref, tcping, requests, python-dateutil, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, PyNaCl, onepush, Markdown, djongo, django-cors-headers, botocore, s3transfer, PyGithub, boto3
[19:30:23.386]   Running setup.py install for Unipath: started
[19:30:23.600]   Running setup.py install for Unipath: finished with status 'done'
[19:30:25.526]   Running setup.py install for tcping: started
[19:30:25.744]   Running setup.py install for tcping: finished with status 'done'
[19:30:27.783]   Running setup.py install for djongo: started
[19:30:28.057]   Running setup.py install for djongo: finished with status 'done'
[19:30:28.954] Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 idna-3.2 importlib-metadata-4.11.3 jmespath-0.10.0 onepush-1.1.1 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 requests-2.26.0 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.8.0
[19:30:28.954] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[19:30:29.033] WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
[19:30:29.033] You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
[19:30:29.300] Traceback (most recent call last):
[19:30:29.301]   File "/vercel/path1/manage.py", line 22, in <module>
[19:30:29.301]     main()
[19:30:29.301]   File "/vercel/path1/manage.py", line 18, in main
[19:30:29.301]     execute_from_command_line(sys.argv)
[19:30:29.301]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:30:29.301]     utility.execute()
[19:30:29.301]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[19:30:29.301]     settings.INSTALLED_APPS
[19:30:29.301]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[19:30:29.301]     self._setup(name)
[19:30:29.301]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[19:30:29.301]     self._wrapped = Settings(settings_module)
[19:30:29.302]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[19:30:29.302]     mod = importlib.import_module(self.SETTINGS_MODULE)
[19:30:29.302]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:30:29.302]     return _bootstrap._gcd_import(name[level:], package, level)
[19:30:29.302]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:30:29.302]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:30:29.302]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:30:29.302]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:30:29.302]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:30:29.302]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:30:29.302]   File "/vercel/path1/core/settings.py", line 21, in <module>
[19:30:29.302]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[19:30:29.302]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[19:30:29.302]     raise KeyError(key) from None
[19:30:29.302] KeyError: 'DOMAINS'
[19:30:29.376] Traceback (most recent call last):
[19:30:29.376]   File "/vercel/path1/manage.py", line 22, in <module>
[19:30:29.376]     main()
[19:30:29.376]   File "/vercel/path1/manage.py", line 18, in main
[19:30:29.376]     execute_from_command_line(sys.argv)
[19:30:29.376]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:30:29.377]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[19:30:29.377]     settings.INSTALLED_APPS
[19:30:29.377]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[19:30:29.377]     self._setup(name)
[19:30:29.377]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[19:30:29.377]     self._wrapped = Settings(settings_module)
[19:30:29.377]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[19:30:29.377]     mod = importlib.import_module(self.SETTINGS_MODULE)
[19:30:29.377]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:30:29.377]     return _bootstrap._gcd_import(name[level:], package, level)
[19:30:29.377]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:30:29.377]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:30:29.377]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:30:29.377]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:30:29.377]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:30:29.378]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:30:29.378]   File "/vercel/path1/core/settings.py", line 21, in <module>
[19:30:29.378]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[19:30:29.378]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[19:30:29.378]     raise KeyError(key) from None
[19:30:29.378] KeyError: 'DOMAINS'
[19:30:29.390] Error: Command "./migrate.sh" exited with 1

### 复现链接

[https://vercel.com/yinlinghunjiang/qexo/5ZzjLopn3boKJofx3Q5655JRFXdm](https://vercel.com/yinlinghunjiang/qexo/5ZzjLopn3boKJofx3Q5655JRFXdm)

### 截图

![trace5](https://user-images.githubusercontent.com/68178871/163673566-08280bac-1b1f-4aaa-b6af-3c4f889b0f99.png)
![trace6](https://user-images.githubusercontent.com/68178871/163673568-2044123b-51de-426f-8d71-8809ab805f81.png)
![trace7](https://user-images.githubusercontent.com/68178871/163673569-bf5fa83f-1563-460b-ae03-69170032c400.png)
![trace1](https://user-images.githubusercontent.com/68178871/163673570-4c2b8b53-75d0-4eb1-9c91-64c8eeb1c020.png)
![trace2](https://user-images.githubusercontent.com/68178871/163673571-6c162683-9398-4575-b703-905c57c225a6.png)
![trace3](https://user-images.githubusercontent.com/68178871/163673572-de8856e4-4496-4ba3-bc94-20f81c88a081.png)
![trace4](https://user-images.githubusercontent.com/68178871/163673574-87935423-d6fb-4cb7-a10f-35fbc5ab9c8c.png)

**Comment by minterjia** [comment]
解决了吗
