### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by cxl2020MC** [Qexo/Qexo#143]
### Qexo 版本

最新

### 问题描述

安装错误

### 截图

[22:07:18] Cloning github.com/cxl2020MC/Qexo (Branch: main, Commit: 6fadc83)
[22:07:19] Cloning completed: 509.847ms
[22:07:19] Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[22:07:19] Installing build runtime...
[22:07:21] Build runtime installed: 1.703s
[22:07:21] Installing build runtime...
[22:07:24] Build runtime installed: 3.153s
[22:07:25] Looking up build cache...
[22:07:25] Build Cache not found
[22:07:26] Collecting asgiref==3.4.1
[22:07:26]   Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
[22:07:26] Collecting autopep8==1.5.7
[22:07:26]   Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
[22:07:26]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 KB 7.0 MB/s eta 0:00:00
[22:07:26] Collecting beautifulsoup4==4.10.0
[22:07:26]   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
[22:07:26]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 19.0 MB/s eta 0:00:00
[22:07:26] Collecting boto==2.49.0
[22:07:26]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[22:07:26]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 81.9 MB/s eta 0:00:00
[22:07:26] Collecting boto3==1.20.23
[22:07:26]   Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
[22:07:26]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 KB 27.9 MB/s eta 0:00:00
[22:07:27] Collecting botocore==1.23.23
[22:07:27]   Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
[22:07:27]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 108.4 MB/s eta 0:00:00
[22:07:27] Collecting certifi==2021.5.30
[22:07:27]   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
[22:07:27]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 29.1 MB/s eta 0:00:00
[22:07:27] Collecting cffi==1.15.0
[22:07:27]   Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
[22:07:27]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 KB 49.9 MB/s eta 0:00:00
[22:07:27] Collecting charset-normalizer==2.0.4
[22:07:27]   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
[22:07:27] Collecting click==8.0.1
[22:07:27]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[22:07:27]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 19.8 MB/s eta 0:00:00
[22:07:27] Collecting colorama==0.4.4
[22:07:27]   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
[22:07:27] Collecting Deprecated==1.2.13
[22:07:27]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[22:07:27] Collecting dj-database-url==0.5.0
[22:07:27]   Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
[22:07:28] Collecting Django==3.0.5
[22:07:28]   Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 107.2 MB/s eta 0:00:00
[22:07:28] Collecting djongo==1.3.6
[22:07:28]   Downloading djongo-1.3.6.tar.gz (331 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 KB 40.1 MB/s eta 0:00:00
[22:07:28]   Preparing metadata (setup.py): started
[22:07:28]   Preparing metadata (setup.py): finished with status 'done'
[22:07:28] Collecting django-cors-headers==3.10.1
[22:07:28]   Downloading django_cors_headers-3.10.1-py3-none-any.whl (12 kB)
[22:07:28] Collecting dnspython==1.16.0
[22:07:28]   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 KB 29.9 MB/s eta 0:00:00
[22:07:28] Collecting gunicorn==20.1.0
[22:07:28]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 19.1 MB/s eta 0:00:00
[22:07:28] Collecting idna==3.2
[22:07:28]   Downloading idna-3.2-py3-none-any.whl (59 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 KB 12.6 MB/s eta 0:00:00
[22:07:28] Collecting jmespath==0.10.0
[22:07:28]   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
[22:07:28] Collecting prettytable==2.2.0
[22:07:28]   Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
[22:07:28] Collecting pyasn1==0.4.8
[22:07:28]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 15.1 MB/s eta 0:00:00
[22:07:28] Collecting pycodestyle==2.7.0
[22:07:28]   Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 9.2 MB/s eta 0:00:00
[22:07:28] Collecting pycparser==2.21
[22:07:28]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 23.4 MB/s eta 0:00:00
[22:07:28] Collecting PyGithub==1.55
[22:07:28]   Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
[22:07:28]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 KB 42.8 MB/s eta 0:00:00
[22:07:28] Collecting PyJWT==2.3.0
[22:07:28]   Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
[22:07:29] Collecting pymongo==3.12.0
[22:07:29]   Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 KB 39.5 MB/s eta 0:00:00
[22:07:29] Collecting PyNaCl==1.4.0
[22:07:29]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 KB 80.7 MB/s eta 0:00:00
[22:07:29] Collecting python-dateutil==2.8.2
[22:07:29]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 46.6 MB/s eta 0:00:00
[22:07:29] Collecting python-decouple==3.4
[22:07:29]   Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
[22:07:29] Collecting pytz==2021.1
[22:07:29]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 KB 60.3 MB/s eta 0:00:00
[22:07:29] Collecting requests==2.26.0
[22:07:29]   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 14.0 MB/s eta 0:00:00
[22:07:29] Collecting rsa==4.7.2
[22:07:29]   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
[22:07:29] Collecting s3transfer==0.5.0
[22:07:29]   Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
[22:07:29]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 KB 17.8 MB/s eta 0:00:00
[22:07:29] Collecting six==1.16.0
[22:07:29]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[22:07:29] Collecting soupsieve==2.2.1
[22:07:29]   Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
[22:07:29] Collecting sqlparse==0.2.4
[22:07:29]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[22:07:29] Collecting tcping==0.1.1rc1
[22:07:29]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[22:07:29]   Preparing metadata (setup.py): started
[22:07:29]   Preparing metadata (setup.py): finished with status 'done'
[22:07:29] Collecting toml==0.10.2
[22:07:29]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[22:07:30] Collecting ujson==4.1.0
[22:07:30]   Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
[22:07:30]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 KB 28.9 MB/s eta 0:00:00
[22:07:30] Collecting Unipath==1.1
[22:07:30]   Downloading Unipath-1.1.tar.gz (30 kB)
[22:07:30]   Preparing metadata (setup.py): started
[22:07:30]   Preparing metadata (setup.py): finished with status 'done'
[22:07:30] Collecting urllib3==1.26.7
[22:07:30]   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
[22:07:30]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 KB 7.1 MB/s eta 0:00:00
[22:07:30] Collecting wcwidth==0.2.5
[22:07:30]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[22:07:30] Collecting whitenoise==5.3.0
[22:07:30]   Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
[22:07:30] Collecting wrapt==1.13.3
[22:07:30]   Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
[22:07:30]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 KB 13.2 MB/s eta 0:00:00
[22:07:30] Collecting Markdown==3.3.6
[22:07:30]   Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
[22:07:30]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 15.1 MB/s eta 0:00:00
[22:07:30] Collecting html2text==2020.1.16
[22:07:30]   Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
[22:07:30] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[22:07:31] Collecting importlib-metadata>=4.4
[22:07:31]   Downloading importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
[22:07:31] Collecting zipp>=0.5
[22:07:31]   Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
[22:07:31] Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
[22:07:31] Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
[22:07:31] Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
[22:07:31] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, dj-database-url, certifi, boto, zipp, wrapt, whitenoise, urllib3, ujson, toml, soupsieve, six, rsa, pymongo, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, html2text, gunicorn, dnspython, colorama, click, charset-normalizer, asgiref, tcping, requests, python-dateutil, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, PyNaCl, Markdown, djongo, django-cors-headers, botocore, s3transfer, PyGithub, boto3
[22:07:31]   Running setup.py install for Unipath: started
[22:07:32]   Running setup.py install for Unipath: finished with status 'done'
[22:07:33]   Running setup.py install for tcping: started
[22:07:34]   Running setup.py install for tcping: finished with status 'done'
[22:07:36]   Running setup.py install for djongo: started
[22:07:36]   Running setup.py install for djongo: finished with status 'done'
[22:07:37] Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 html2text-2020.1.16 idna-3.2 importlib-metadata-4.11.3 jmespath-0.10.0 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 requests-2.26.0 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.8.0
[22:07:37] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[22:07:37] Traceback (most recent call last):
[22:07:37]   File "/vercel/path1/manage.py", line 22, in <module>
[22:07:37]     main()
[22:07:37]   File "/vercel/path1/manage.py", line 18, in main
[22:07:37]     execute_from_command_line(sys.argv)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[22:07:37]     utility.execute()
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[22:07:37]     settings.INSTALLED_APPS
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[22:07:37]     self._setup(name)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[22:07:37]     self._wrapped = Settings(settings_module)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[22:07:37]     mod = importlib.import_module(self.SETTINGS_MODULE)
[22:07:37]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[22:07:37]     return _bootstrap._gcd_import(name[level:], package, level)
[22:07:37]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[22:07:37]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[22:07:37]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[22:07:37]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[22:07:37]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[22:07:37]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[22:07:37]   File "/vercel/path1/core/settings.py", line 21, in <module>
[22:07:37]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[22:07:37]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[22:07:37]     raise KeyError(key) from None
[22:07:37] KeyError: 'DOMAINS'
[22:07:37] Traceback (most recent call last):
[22:07:37]   File "/vercel/path1/manage.py", line 22, in <module>
[22:07:37]     main()
[22:07:37]   File "/vercel/path1/manage.py", line 18, in main
[22:07:37]     execute_from_command_line(sys.argv)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[22:07:37]     utility.execute()
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[22:07:37]     settings.INSTALLED_APPS
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[22:07:37]     self._setup(name)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[22:07:37]     self._wrapped = Settings(settings_module)
[22:07:37]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[22:07:37]     mod = importlib.import_module(self.SETTINGS_MODULE)
[22:07:37]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[22:07:37]     return _bootstrap._gcd_import(name[level:], package, level)
[22:07:37]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[22:07:37]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[22:07:37]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[22:07:37]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[22:07:37]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[22:07:37]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[22:07:37]   File "/vercel/path1/core/settings.py", line 21, in <module>
[22:07:37]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[22:07:37]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[22:07:37]     raise KeyError(key) from None
[22:07:37] KeyError: 'DOMAINS'
[22:07:37] Error: Command "./migrate.sh" exited with 1

**Comment by am-abudu** [comment]
为环境变量配置问题，请见文档

**Comment by cxl2020MC** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/69844153/166617691-d4067a3e-02a4-44f7-94d5-954be7a12555.png">
数据库链接地址是这个吧

**Comment by cxl2020MC** [comment]
ok了感谢
