### ISSUE TITLE
Vercel一键部署报错

### ISSUE THREAD

**Issue by OrdChaos** [Qexo/Qexo#159]
### Qexo 版本

latest

### 问题描述

如题，一键部署时build阶段报错
下为输出
```
[13:20:21.470] Cloning github.com/OrdChaos/Qexo (Branch: main, Commit: de379ae)
[13:20:22.012] Cloning completed: 540.942ms
[13:20:22.086] Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[13:20:22.387] Installing build runtime...
[13:20:24.287] Build runtime installed: 1.900s
[13:20:24.314] Installing build runtime...
[13:20:26.710] Build runtime installed: 2.396s
[13:20:27.798] Looking up build cache...
[13:20:28.062] Build Cache not found
[13:20:28.745] Collecting asgiref==3.4.1
[13:20:28.813]   Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
[13:20:28.854] Collecting autopep8==1.5.7
[13:20:28.894]   Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
[13:20:28.906]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 KB 4.3 MB/s eta 0:00:00
[13:20:28.946] Collecting beautifulsoup4==4.10.0
[13:20:28.960]   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
[13:20:28.976]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 6.7 MB/s eta 0:00:00
[13:20:29.023] Collecting boto==2.49.0
[13:20:29.038]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[13:20:29.083]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 31.6 MB/s eta 0:00:00
[13:20:29.556] Collecting boto3==1.20.23
[13:20:29.573]   Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
[13:20:29.580]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 KB 27.1 MB/s eta 0:00:00
[13:20:30.161] Collecting botocore==1.23.23
[13:20:30.177]   Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
[13:20:30.288]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 78.5 MB/s eta 0:00:00
[13:20:30.356] Collecting certifi==2021.5.30
[13:20:30.373]   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
[13:20:30.381]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 28.1 MB/s eta 0:00:00
[13:20:30.597] Collecting cffi==1.15.0
[13:20:30.612]   Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
[13:20:30.624]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 KB 44.0 MB/s eta 0:00:00
[13:20:30.663] Collecting charset-normalizer==2.0.4
[13:20:30.682]   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
[13:20:30.728] Collecting click==8.0.1
[13:20:30.744]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[13:20:30.751]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 18.3 MB/s eta 0:00:00
[13:20:30.791] Collecting colorama==0.4.4
[13:20:30.807]   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
[13:20:30.846] Collecting Deprecated==1.2.13
[13:20:30.861]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[13:20:30.893] Collecting dj-database-url==0.5.0
[13:20:30.908]   Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
[13:20:31.033] Collecting Django==3.0.5
[13:20:31.065]   Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
[13:20:31.156]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 85.0 MB/s eta 0:00:00
[13:20:31.239] Collecting djongo==1.3.6
[13:20:31.256]   Downloading djongo-1.3.6.tar.gz (331 kB)
[13:20:31.268]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 KB 36.9 MB/s eta 0:00:00
[13:20:31.292]   Preparing metadata (setup.py): started
[13:20:31.480]   Preparing metadata (setup.py): finished with status 'done'
[13:20:31.528] Collecting django-cors-headers==3.10.1
[13:20:31.544]   Downloading django_cors_headers-3.10.1-py3-none-any.whl (12 kB)
[13:20:31.579] Collecting dnspython==1.16.0
[13:20:31.608]   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
[13:20:31.617]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 KB 28.2 MB/s eta 0:00:00
[13:20:31.658] Collecting gunicorn==20.1.0
[13:20:31.672]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[13:20:31.679]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 17.0 MB/s eta 0:00:00
[13:20:31.711] Collecting idna==3.2
[13:20:31.733]   Downloading idna-3.2-py3-none-any.whl (59 kB)
[13:20:31.739]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 KB 13.2 MB/s eta 0:00:00
[13:20:31.769] Collecting jmespath==0.10.0
[13:20:31.784]   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
[13:20:31.821] Collecting prettytable==2.2.0
[13:20:31.842]   Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
[13:20:31.900] Collecting pyasn1==0.4.8
[13:20:31.916]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[13:20:31.923]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 15.9 MB/s eta 0:00:00
[13:20:31.954] Collecting pycodestyle==2.7.0
[13:20:31.975]   Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
[13:20:31.982]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 9.2 MB/s eta 0:00:00
[13:20:32.010] Collecting pycparser==2.21
[13:20:32.026]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[13:20:32.033]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 25.0 MB/s eta 0:00:00
[13:20:32.076] Collecting PyGithub==1.55
[13:20:32.092]   Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
[13:20:32.102]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 KB 41.7 MB/s eta 0:00:00
[13:20:32.144] Collecting PyJWT==2.3.0
[13:20:32.159]   Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
[13:20:32.622] Collecting pymongo==3.12.0
[13:20:32.640]   Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
[13:20:32.653]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 KB 54.3 MB/s eta 0:00:00
[13:20:32.707] Collecting PyNaCl==1.4.0
[13:20:32.726]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[13:20:32.743]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 KB 69.2 MB/s eta 0:00:00
[13:20:32.783] Collecting python-dateutil==2.8.2
[13:20:32.798]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[13:20:32.809]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 31.9 MB/s eta 0:00:00
[13:20:32.838] Collecting python-decouple==3.4
[13:20:32.854]   Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
[13:20:32.950] Collecting pytz==2021.1
[13:20:32.967]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[13:20:32.979]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 KB 54.3 MB/s eta 0:00:00
[13:20:33.047] Collecting requests==2.26.0
[13:20:33.061]   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
[13:20:33.068]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 12.9 MB/s eta 0:00:00
[13:20:33.114] Collecting rsa==4.7.2
[13:20:33.132]   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
[13:20:33.172] Collecting s3transfer==0.5.0
[13:20:33.190]   Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
[13:20:33.198]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 KB 13.6 MB/s eta 0:00:00
[13:20:33.231] Collecting six==1.16.0
[13:20:33.251]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[13:20:33.294] Collecting soupsieve==2.2.1
[13:20:33.309]   Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
[13:20:33.345] Collecting sqlparse==0.2.4
[13:20:33.368]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[13:20:33.402] Collecting tcping==0.1.1rc1
[13:20:33.418]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[13:20:33.426]   Preparing metadata (setup.py): started
[13:20:33.609]   Preparing metadata (setup.py): finished with status 'done'
[13:20:33.639] Collecting toml==0.10.2
[13:20:33.654]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[13:20:33.759] Collecting ujson==4.1.0
[13:20:33.777]   Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
[13:20:33.786]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 KB 29.2 MB/s eta 0:00:00
[13:20:33.811] Collecting Unipath==1.1
[13:20:33.827]   Downloading Unipath-1.1.tar.gz (30 kB)
[13:20:33.837]   Preparing metadata (setup.py): started
[13:20:34.016]   Preparing metadata (setup.py): finished with status 'done'
[13:20:34.073] Collecting urllib3==1.26.7
[13:20:34.088]   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
[13:20:34.096]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 KB 23.9 MB/s eta 0:00:00
[13:20:34.126] Collecting wcwidth==0.2.5
[13:20:34.140]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[13:20:34.184] Collecting whitenoise==5.3.0
[13:20:34.209]   Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
[13:20:34.355] Collecting wrapt==1.13.3
[13:20:34.372]   Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
[13:20:34.378]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 KB 17.6 MB/s eta 0:00:00
[13:20:34.418] Collecting Markdown==3.3.6
[13:20:34.433]   Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
[13:20:34.440]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 19.2 MB/s eta 0:00:00
[13:20:34.471] Collecting html2text==2020.1.16
[13:20:34.486]   Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
[13:20:34.806] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[13:20:35.248] Collecting importlib-metadata>=4.4
[13:20:35.262]   Downloading importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
[13:20:35.344] Collecting zipp>=0.5
[13:20:35.358]   Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
[13:20:35.422] Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
[13:20:35.422] Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
[13:20:35.423] Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
[13:20:35.645] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, dj-database-url, certifi, boto, zipp, wrapt, whitenoise, urllib3, ujson, toml, soupsieve, six, rsa, pymongo, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, html2text, gunicorn, dnspython, colorama, click, charset-normalizer, asgiref, tcping, requests, python-dateutil, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, PyNaCl, Markdown, djongo, django-cors-headers, botocore, s3transfer, PyGithub, boto3
[13:20:35.696]   Running setup.py install for Unipath: started
[13:20:35.910]   Running setup.py install for Unipath: finished with status 'done'
[13:20:37.816]   Running setup.py install for tcping: started
[13:20:38.040]   Running setup.py install for tcping: finished with status 'done'
[13:20:40.071]   Running setup.py install for djongo: started
[13:20:40.346]   Running setup.py install for djongo: finished with status 'done'
[13:20:41.234] Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 html2text-2020.1.16 idna-3.2 importlib-metadata-4.11.4 jmespath-0.10.0 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 requests-2.26.0 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.8.0
[13:20:41.234] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[13:20:41.356] WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
[13:20:41.356] You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
[13:20:41.653] Traceback (most recent call last):
[13:20:41.653]   File "/vercel/path1/manage.py", line 22, in <module>
[13:20:41.653]     main()
[13:20:41.653]   File "/vercel/path1/manage.py", line 18, in main
[13:20:41.653]     execute_from_command_line(sys.argv)
[13:20:41.653]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[13:20:41.653]     utility.execute()
[13:20:41.653]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[13:20:41.653]     settings.INSTALLED_APPS
[13:20:41.653]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[13:20:41.654]     self._setup(name)
[13:20:41.654]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[13:20:41.654]     self._wrapped = Settings(settings_module)
[13:20:41.654]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[13:20:41.654]     mod = importlib.import_module(self.SETTINGS_MODULE)
[13:20:41.654]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[13:20:41.654]     return _bootstrap._gcd_import(name[level:], package, level)
[13:20:41.654]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[13:20:41.654]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[13:20:41.654]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[13:20:41.654]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[13:20:41.654]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[13:20:41.654]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[13:20:41.654]   File "/vercel/path1/core/settings.py", line 21, in <module>
[13:20:41.654]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[13:20:41.654]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[13:20:41.654]     raise KeyError(key) from None
[13:20:41.654] KeyError: 'DOMAINS'
[13:20:41.727] Traceback (most recent call last):
[13:20:41.727]   File "/vercel/path1/manage.py", line 22, in <module>
[13:20:41.728]     main()
[13:20:41.728]   File "/vercel/path1/manage.py", line 18, in main
[13:20:41.728]     execute_from_command_line(sys.argv)
[13:20:41.728]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[13:20:41.728]     utility.execute()
[13:20:41.728]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[13:20:41.728]     settings.INSTALLED_APPS
[13:20:41.728]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[13:20:41.728]     self._setup(name)
[13:20:41.728]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[13:20:41.728]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[13:20:41.728]     mod = importlib.import_module(self.SETTINGS_MODULE)
[13:20:41.728]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[13:20:41.729]     return _bootstrap._gcd_import(name[level:], package, level)
[13:20:41.729]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[13:20:41.729]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[13:20:41.729]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[13:20:41.729]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[13:20:41.729]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[13:20:41.729]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[13:20:41.729]   File "/vercel/path1/core/settings.py", line 21, in <module>
[13:20:41.729]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[13:20:41.729]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[13:20:41.729]     raise KeyError(key) from None
[13:20:41.729] KeyError: 'DOMAINS'
[13:20:41.743] Error: Command "./migrate.sh" exited with 1
```

### 截图

![image](https://user-images.githubusercontent.com/101442840/170853545-a56907ab-bb69-4268-8309-023890bbc336.png)

**Comment by Fgaoxing** [comment]
文档：https://github.com/Qexo/Qexo/wiki/Vercel-%E9%83%A8%E7%BD%B2
检查环境变量`DOMAINS`

**Comment by Fgaoxing** [comment]
@OrdChaos

**Comment by OrdChaos** [comment]
可是我什么环境变量都没配置啊......
都没有让我配置
就是一点一键部署，等了1分钟，然后就这样了
@Fgaoxing

**Comment by Fgaoxing** [comment]
@am-abudu 这环境又有问题了，看看吧

**Comment by am-abudu** [comment]
是让你自己去设置里面写环境变量 然后重新部署一遍

**Comment by Fgaoxing** [comment]
@am-abudu 部署页面没有环境变量

**Comment by Fgaoxing** [comment]
这个我知道，但是第一次部署时，没法设置了

**Comment by Fgaoxing** [comment]
你加个检测吧

**Comment by Fgaoxing** [comment]
不管是一键部署，还是自己传，都一样

**Comment by OrdChaos** [comment]
![image](https://user-images.githubusercontent.com/101442840/170855018-feb72939-80ee-402d-b1c1-0432c50a0f19.png)
然后直接报错

**Comment by am-abudu** [comment]
文档写的很清楚了 自己不看我也没办法

**Comment by OrdChaos** [comment]
所以意思是部署失败然后进项目界面写变量再部署？
文档完全没提首次就会直接失败

**Comment by OrdChaos** [comment]
意思是，好歹加一句话吧

**Comment by Fgaoxing** [comment]
@OrdChaos 
![image](https://user-images.githubusercontent.com/92655031/170855255-8dbf0852-06a1-41d3-9d04-203caf63f27a.png)
