### ISSUE TITLE
dev分支报错

### ISSUE THREAD

**Issue by Fgaoxing** [Qexo/Qexo#166]
### Qexo 版本

dev（1.8）

### 问题描述

```
[19:11:46.709] Retrieving list of deployment files...
[19:11:53.406] Downloading 83 deployment files...
[19:11:56.065] Looking up build cache...
[19:11:56.300] Build Cache not found
[19:11:56.591] Running "vercel build"
[19:11:57.185] Vercel CLI 25.1.1-canary.3 build (beta) — https://vercel.com/feedback
[19:11:57.321] WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[19:11:58.064] Collecting asgiref==3.4.1
[19:11:58.136]   Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
[19:11:58.184] Collecting autopep8==1.5.7
[19:11:58.210]   Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
[19:11:58.223]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.9 MB/s eta 0:00:00
[19:11:58.266] Collecting beautifulsoup4==4.10.0
[19:11:58.281]   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
[19:11:58.298]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 6.3 MB/s eta 0:00:00
[19:11:58.351] Collecting boto==2.49.0
[19:11:58.366]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[19:11:58.414]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 30.2 MB/s eta 0:00:00
[19:11:59.031] Collecting boto3==1.20.23
[19:11:59.046]   Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
[19:11:59.056]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 20.2 MB/s eta 0:00:00
[19:11:59.775] Collecting botocore==1.23.23
[19:11:59.792]   Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
[19:11:59.957]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 52.2 MB/s eta 0:00:00
[19:12:00.040] Collecting certifi==2021.5.30
[19:12:00.056]   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
[19:12:00.065]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 kB 21.4 MB/s eta 0:00:00
[19:12:00.338] Collecting cffi==1.15.0
[19:12:00.353]   Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
[19:12:00.367]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 kB 41.3 MB/s eta 0:00:00
[19:12:00.418] Collecting charset-normalizer==2.0.4
[19:12:00.432]   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
[19:12:00.512] Collecting click==8.0.1
[19:12:00.527]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[19:12:00.536]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 16.4 MB/s eta 0:00:00
[19:12:00.580] Collecting colorama==0.4.4
[19:12:00.595]   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
[19:12:00.641] Collecting Deprecated==1.2.13
[19:12:00.656]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[19:12:00.690] Collecting dj-database-url==0.5.0
[19:12:00.704]   Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
[19:12:00.860] Collecting Django==3.0.5
[19:12:00.880]   Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
[19:12:00.986]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 72.8 MB/s eta 0:00:00
[19:12:01.085] Collecting djongo==1.3.6
[19:12:01.105]   Downloading djongo-1.3.6.tar.gz (331 kB)
[19:12:01.119]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 kB 30.2 MB/s eta 0:00:00
[19:12:01.151]   Preparing metadata (setup.py): started
[19:12:01.372]   Preparing metadata (setup.py): finished with status 'done'
[19:12:01.427] Collecting django-cors-headers==3.10.1
[19:12:01.442]   Downloading django_cors_headers-3.10.1-py3-none-any.whl (12 kB)
[19:12:01.484] Collecting dnspython==1.16.0
[19:12:01.501]   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
[19:12:01.512]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 27.1 MB/s eta 0:00:00
[19:12:01.565] Collecting gunicorn==20.1.0
[19:12:01.580]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[19:12:01.588]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 13.7 MB/s eta 0:00:00
[19:12:01.626] Collecting idna==3.2
[19:12:01.647]   Downloading idna-3.2-py3-none-any.whl (59 kB)
[19:12:01.655]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 9.4 MB/s eta 0:00:00
[19:12:01.690] Collecting jmespath==0.10.0
[19:12:01.705]   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
[19:12:01.749] Collecting prettytable==2.2.0
[19:12:01.770]   Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
[19:12:01.839] Collecting pyasn1==0.4.8
[19:12:01.853]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[19:12:01.862]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 12.5 MB/s eta 0:00:00
[19:12:01.897] Collecting pycodestyle==2.7.0
[19:12:01.912]   Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
[19:12:01.920]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 6.2 MB/s eta 0:00:00
[19:12:01.952] Collecting pycparser==2.21
[19:12:01.974]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[19:12:01.984]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 15.7 MB/s eta 0:00:00
[19:12:02.035] Collecting PyGithub==1.55
[19:12:02.051]   Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
[19:12:02.064]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 kB 30.6 MB/s eta 0:00:00
[19:12:02.115] Collecting PyJWT==2.3.0
[19:12:02.130]   Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
[19:12:02.707] Collecting pymongo==3.12.0
[19:12:02.725]   Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
[19:12:02.740]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 46.9 MB/s eta 0:00:00
[19:12:02.812] Collecting PyNaCl==1.4.0
[19:12:02.830]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[19:12:02.849]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 kB 60.8 MB/s eta 0:00:00
[19:12:02.897] Collecting python-dateutil==2.8.2
[19:12:02.912]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[19:12:02.924]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 32.1 MB/s eta 0:00:00
[19:12:02.956] Collecting python-decouple==3.4
[19:12:02.971]   Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
[19:12:03.081] Collecting pytz==2021.1
[19:12:03.097]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[19:12:03.111]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 kB 45.4 MB/s eta 0:00:00
[19:12:03.195] Collecting requests==2.26.0
[19:12:03.211]   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
[19:12:03.219]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 9.8 MB/s eta 0:00:00
[19:12:03.265] Collecting rsa==4.7.2
[19:12:03.280]   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
[19:12:03.326] Collecting s3transfer==0.5.0
[19:12:03.341]   Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
[19:12:03.349]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 14.5 MB/s eta 0:00:00
[19:12:03.387] Collecting six==1.16.0
[19:12:03.402]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[19:12:03.458] Collecting soupsieve==2.2.1
[19:12:03.475]   Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
[19:12:03.516] Collecting sqlparse==0.2.4
[19:12:03.532]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[19:12:03.566] Collecting tcping==0.1.1rc1
[19:12:03.584]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[19:12:03.592]   Preparing metadata (setup.py): started
[19:12:03.809]   Preparing metadata (setup.py): finished with status 'done'
[19:12:03.843] Collecting toml==0.10.2
[19:12:03.858]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[19:12:03.990] Collecting ujson==4.1.0
[19:12:04.017]   Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
[19:12:04.027]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 kB 27.2 MB/s eta 0:00:00
[19:12:04.059] Collecting Unipath==1.1
[19:12:04.075]   Downloading Unipath-1.1.tar.gz (30 kB)
[19:12:04.088]   Preparing metadata (setup.py): started
[19:12:04.308]   Preparing metadata (setup.py): finished with status 'done'
[19:12:04.379] Collecting urllib3==1.26.7
[19:12:04.394]   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
[19:12:04.404]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 kB 23.1 MB/s eta 0:00:00
[19:12:04.438] Collecting wcwidth==0.2.5
[19:12:04.452]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[19:12:04.505] Collecting whitenoise==5.3.0
[19:12:04.520]   Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
[19:12:04.696] Collecting wrapt==1.13.3
[19:12:04.711]   Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
[19:12:04.721]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 12.1 MB/s eta 0:00:00
[19:12:04.768] Collecting Markdown==3.3.6
[19:12:04.785]   Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
[19:12:04.794]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 16.8 MB/s eta 0:00:00
[19:12:04.835] Collecting html2text==2020.1.16
[19:12:04.851]   Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
[19:12:05.313] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[19:12:05.998] Collecting importlib-metadata>=4.4
[19:12:06.013]   Downloading importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
[19:12:06.123] Collecting zipp>=0.5
[19:12:06.138]   Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
[19:12:06.217] Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
[19:12:06.218] Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
[19:12:06.218] Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
[19:12:06.485] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, dj-database-url, certifi, boto, zipp, wrapt, whitenoise, urllib3, ujson, toml, soupsieve, six, rsa, pymongo, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, html2text, gunicorn, dnspython, colorama, click, charset-normalizer, asgiref, tcping, requests, python-dateutil, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, PyNaCl, Markdown, djongo, django-cors-headers, botocore, s3transfer, PyGithub, boto3
[19:12:06.546]   Running setup.py install for Unipath: started
[19:12:06.804]   Running setup.py install for Unipath: finished with status 'done'
[19:12:09.199]   Running setup.py install for tcping: started
[19:12:09.475]   Running setup.py install for tcping: finished with status 'done'
[19:12:12.095]   Running setup.py install for djongo: started
[19:12:12.433]   Running setup.py install for djongo: finished with status 'done'
[19:12:13.546] Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 html2text-2020.1.16 idna-3.2 importlib-metadata-4.11.4 jmespath-0.10.0 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 requests-2.26.0 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.8.0
[19:12:13.547] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[19:12:14.527] Traceback (most recent call last):
[19:12:14.529]   File "/vercel/path1/manage.py", line 22, in <module>
[19:12:14.530]     main()
[19:12:14.530]   File "/vercel/path1/manage.py", line 18, in main
[19:12:14.530]     execute_from_command_line(sys.argv)
[19:12:14.530]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:12:14.530]     utility.execute()
[19:12:14.531]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
[19:12:14.531]     self.fetch_command(subcommand).run_from_argv(self.argv)
[19:12:14.531]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
[19:12:14.531]     self.execute(*args, **cmd_options)
[19:12:14.531]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 366, in execute
[19:12:14.531]     self.check()
[19:12:14.532]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
[19:12:14.532]     all_issues = self._run_checks(
[19:12:14.532]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 382, in _run_checks
[19:12:14.532]     return checks.run_checks(**kwargs)
[19:12:14.532]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
[19:12:14.532]     new_errors = check(app_configs=app_configs)
[19:12:14.532]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
[19:12:14.532]     return check_resolver(resolver)
[19:12:14.533]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
[19:12:14.533]     return check_method()
[19:12:14.533]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 407, in check
[19:12:14.533]     for pattern in self.url_patterns:
[19:12:14.533]   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
[19:12:14.533]     res = instance.__dict__[self.name] = self.func(instance)
[19:12:14.533]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 588, in url_patterns
[19:12:14.533]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[19:12:14.533]   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
[19:12:14.533]     res = instance.__dict__[self.name] = self.func(instance)
[19:12:14.534]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
[19:12:14.534]     return import_module(self.urlconf_name)
[19:12:14.534]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:12:14.534]     return _bootstrap._gcd_import(name[level:], package, level)
[19:12:14.534]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:12:14.534]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:12:14.534]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:12:14.534]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:12:14.535]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:12:14.535]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:12:14.535]   File "/vercel/path1/core/urls.py", line 1, in <module>
[19:12:14.535]     from hexoweb.views import *
[19:12:14.535]   File "/vercel/path1/hexoweb/views.py", line 7, in <module>
[19:12:14.535]     from .api import *
[19:12:14.535]   File "/vercel/path1/hexoweb/api.py", line 1, in <module>
[19:12:14.535]     from .functions import *
[19:12:14.535]   File "/vercel/path1/hexoweb/functions.py", line 26, in <module>
[19:12:14.536]     Provider = json.loads(SettingModel.objects.get(name="PROVIDER").content)
[19:12:14.536]   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
[19:12:14.536]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[19:12:14.536]   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 415, in get
[19:12:14.536]     raise self.model.DoesNotExist(
[19:12:14.536] hexoweb.models.SettingModel.DoesNotExist: SettingModel matching query does not exist.
[19:12:15.764] Traceback (most recent call last):
[19:12:15.764]   File "/vercel/path1/manage.py", line 22, in <module>
[19:12:15.764]     main()
[19:12:15.764]   File "/vercel/path1/manage.py", line 18, in main
[19:12:15.764]     execute_from_command_line(sys.argv)
[19:12:15.764]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:12:15.764]     utility.execute()
[19:12:15.764]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
[19:12:15.765]     self.fetch_command(subcommand).run_from_argv(self.argv)
[19:12:15.765]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
[19:12:15.765]     self.execute(*args, **cmd_options)
[19:12:15.765]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 366, in execute
[19:12:15.765]     self.check()
[19:12:15.765]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
[19:12:15.766]     all_issues = self._run_checks(
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
[19:12:15.767]     issues.extend(super()._run_checks(**kwargs))
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 382, in _run_checks
[19:12:15.767]     return checks.run_checks(**kwargs)
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
[19:12:15.767]     new_errors = check(app_configs=app_configs)
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
[19:12:15.767]     return check_resolver(resolver)
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
[19:12:15.767]     return check_method()
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 407, in check
[19:12:15.767]     for pattern in self.url_patterns:
[19:12:15.767]   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
[19:12:15.767]     res = instance.__dict__[self.name] = self.func(instance)
[19:12:15.768]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 588, in url_patterns
[19:12:15.768]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[19:12:15.768]   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
[19:12:15.768]     res = instance.__dict__[self.name] = self.func(instance)
[19:12:15.768]   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
[19:12:15.768]     return import_module(self.urlconf_name)
[19:12:15.768]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:12:15.768]     return _bootstrap._gcd_import(name[level:], package, level)
[19:12:15.768]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:12:15.768]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:12:15.768]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:12:15.768]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:12:15.769]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:12:15.769]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:12:15.769]   File "/vercel/path1/core/urls.py", line 1, in <module>
[19:12:15.769]     from hexoweb.views import *
[19:12:15.769]   File "/vercel/path1/hexoweb/views.py", line 7, in <module>
[19:12:15.769]     from .api import *
[19:12:15.769]   File "/vercel/path1/hexoweb/api.py", line 1, in <module>
[19:12:15.769]     from .functions import *
[19:12:15.769]   File "/vercel/path1/hexoweb/functions.py", line 26, in <module>
[19:12:15.769]     Provider = json.loads(SettingModel.objects.get(name="PROVIDER").content)
[19:12:15.769]   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
[19:12:15.769]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[19:12:15.769]   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 415, in get
[19:12:15.770]     raise self.model.DoesNotExist(
[19:12:15.770] hexoweb.models.SettingModel.DoesNotExist: SettingModel matching query does not exist.
[19:12:16.311] Error! Command "./migrate.sh" exited with 1
[19:12:16.419] Error: Command "vercel build" exited with 1
```

### 截图

无

**Comment by Fgaoxing** [comment]
我也不知道为啥报错`hexoweb.models.SettingModel.DoesNotExist: SettingModel matching query does not exist.`

**Comment by Fgaoxing** [comment]
@am-abudu

**Comment by Fgaoxing** [comment]
我看了有这个函数，有啊！

**Comment by am-abudu** [comment]
Dev分支目前是个半成品，存在问题很正常
