### ISSUE TITLE
Vercel 一键部署出现错误

### ISSUE THREAD

**Issue by dengchangdong** [Qexo/Qexo#196]
### Qexo 版本

v1.5.3

### 问题描述

**错误代码如下：**

```
[19:39:59.059] Cloning github.com/dengchangdong/hexo-admin (Branch: main, Commit: c8aaf25)
[19:39:59.469] Cloning completed: 410.059ms
[19:40:00.291] Looking up build cache...
[19:40:00.595] Build Cache not found
[19:40:00.819] Running "vercel build"
[19:40:01.353] Vercel CLI 27.3.7
[19:40:01.468] WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[19:40:02.065] Collecting asgiref==3.4.1
[19:40:02.081]   Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
[19:40:02.109] Collecting autopep8==1.5.7
[19:40:02.115]   Downloading autopep8-1.5.7-py2.py3-none-any.whl (45 kB)
[19:40:02.121]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 9.9 MB/s eta 0:00:00
[19:40:02.146] Collecting beautifulsoup4==4.10.0
[19:40:02.150]   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
[19:40:02.157]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 21.5 MB/s eta 0:00:00
[19:40:02.192] Collecting boto==2.49.0
[19:40:02.213]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[19:40:02.232]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 85.1 MB/s eta 0:00:00
[19:40:02.702] Collecting boto3==1.20.23
[19:40:02.708]   Downloading boto3-1.20.23-py3-none-any.whl (131 kB)
[19:40:02.716]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 23.0 MB/s eta 0:00:00
[19:40:03.283] Collecting botocore==1.23.23
[19:40:03.290]   Downloading botocore-1.23.23-py3-none-any.whl (8.4 MB)
[19:40:03.371]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 107.6 MB/s eta 0:00:00
[19:40:03.430] Collecting certifi==2021.5.30
[19:40:03.442]   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
[19:40:03.449]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 kB 29.5 MB/s eta 0:00:00
[19:40:03.704] Collecting cffi==1.15.0
[19:40:03.710]   Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
[19:40:03.721]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.3/444.3 kB 58.1 MB/s eta 0:00:00
[19:40:03.751] Collecting charset-normalizer==2.0.4
[19:40:03.755]   Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
[19:40:03.790] Collecting click==8.0.1
[19:40:03.794]   Downloading click-8.0.1-py3-none-any.whl (97 kB)
[19:40:03.801]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 21.1 MB/s eta 0:00:00
[19:40:03.828] Collecting colorama==0.4.4
[19:40:03.832]   Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
[19:40:03.862] Collecting Deprecated==1.2.13
[19:40:03.866]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[19:40:03.885] Collecting dj-database-url==0.5.0
[19:40:03.889]   Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
[19:40:04.008] Collecting Django==3.0.5
[19:40:04.013]   Downloading Django-3.0.5-py3-none-any.whl (7.5 MB)
[19:40:04.083]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 110.0 MB/s eta 0:00:00
[19:40:04.155] Collecting djongo==1.3.6
[19:40:04.161]   Downloading djongo-1.3.6.tar.gz (331 kB)
[19:40:04.171]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 kB 47.0 MB/s eta 0:00:00
[19:40:04.196]   Preparing metadata (setup.py): started
[19:40:04.381]   Preparing metadata (setup.py): finished with status 'done'
[19:40:04.416] Collecting django-cors-headers==3.10.1
[19:40:04.421]   Downloading django_cors_headers-3.10.1-py3-none-any.whl (12 kB)
[19:40:04.443] Collecting dnspython==1.16.0
[19:40:04.449]   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
[19:40:04.457]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 35.4 MB/s eta 0:00:00
[19:40:04.488] Collecting gunicorn==20.1.0
[19:40:04.492]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[19:40:04.499]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 17.2 MB/s eta 0:00:00
[19:40:04.521] Collecting idna==3.2
[19:40:04.524]   Downloading idna-3.2-py3-none-any.whl (59 kB)
[19:40:04.530]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 13.7 MB/s eta 0:00:00
[19:40:04.550] Collecting jmespath==0.10.0
[19:40:04.554]   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
[19:40:04.580] Collecting prettytable==2.2.0
[19:40:04.585]   Downloading prettytable-2.2.0-py3-none-any.whl (23 kB)
[19:40:04.632] Collecting pyasn1==0.4.8
[19:40:04.637]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[19:40:04.645]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 14.7 MB/s eta 0:00:00
[19:40:04.673] Collecting pycodestyle==2.7.0
[19:40:04.676]   Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
[19:40:04.683]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 8.2 MB/s eta 0:00:00
[19:40:04.702] Collecting pycparser==2.21
[19:40:04.705]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[19:40:04.713]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 24.1 MB/s eta 0:00:00
[19:40:04.745] Collecting PyGithub==1.55
[19:40:04.751]   Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
[19:40:04.760]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 kB 42.4 MB/s eta 0:00:00
[19:40:04.792] Collecting PyJWT==2.3.0
[19:40:04.796]   Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
[19:40:05.258] Collecting pymongo==3.12.0
[19:40:05.266]   Downloading pymongo-3.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (531 kB)
[19:40:05.277]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 61.1 MB/s eta 0:00:00
[19:40:05.321] Collecting PyNaCl==1.4.0
[19:40:05.329]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[19:40:05.345]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.1/961.1 kB 71.0 MB/s eta 0:00:00
[19:40:05.373] Collecting python-dateutil==2.8.2
[19:40:05.377]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[19:40:05.386]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 41.0 MB/s eta 0:00:00
[19:40:05.402] Collecting python-decouple==3.4
[19:40:05.406]   Downloading python_decouple-3.4-py3-none-any.whl (9.5 kB)
[19:40:05.490] Collecting pytz==2021.1
[19:40:05.496]   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
[19:40:05.507]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 kB 60.3 MB/s eta 0:00:00
[19:40:05.565] Collecting requests==2.27.1
[19:40:05.569]   Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
[19:40:05.575]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 12.4 MB/s eta 0:00:00
[19:40:05.604] Collecting rsa==4.7.2
[19:40:05.608]   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
[19:40:05.639] Collecting s3transfer==0.5.0
[19:40:05.642]   Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
[19:40:05.651]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 12.6 MB/s eta 0:00:00
[19:40:05.673] Collecting six==1.16.0
[19:40:05.677]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[19:40:05.709] Collecting soupsieve==2.2.1
[19:40:05.715]   Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
[19:40:05.739] Collecting sqlparse==0.2.4
[19:40:05.744]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[19:40:05.763] Collecting tcping==0.1.1rc1
[19:40:05.768]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[19:40:05.775]   Preparing metadata (setup.py): started
[19:40:05.953]   Preparing metadata (setup.py): finished with status 'done'
[19:40:05.974] Collecting toml==0.10.2
[19:40:05.979]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[19:40:06.079] Collecting ujson==4.1.0
[19:40:06.084]   Downloading ujson-4.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (179 kB)
[19:40:06.093]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.5/179.5 kB 32.1 MB/s eta 0:00:00
[19:40:06.107] Collecting Unipath==1.1
[19:40:06.112]   Downloading Unipath-1.1.tar.gz (30 kB)
[19:40:06.121]   Preparing metadata (setup.py): started
[19:40:06.295]   Preparing metadata (setup.py): finished with status 'done'
[19:40:06.346] Collecting urllib3==1.26.7
[19:40:06.351]   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
[19:40:06.360]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 kB 23.7 MB/s eta 0:00:00
[19:40:06.382] Collecting wcwidth==0.2.5
[19:40:06.390]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[19:40:06.423] Collecting whitenoise==5.3.0
[19:40:06.428]   Downloading whitenoise-5.3.0-py2.py3-none-any.whl (19 kB)
[19:40:06.561] Collecting wrapt==1.13.3
[19:40:06.566]   Downloading wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
[19:40:06.572]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 16.9 MB/s eta 0:00:00
[19:40:06.602] Collecting Markdown==3.3.6
[19:40:06.612]   Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
[19:40:06.617]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 20.3 MB/s eta 0:00:00
[19:40:06.637] Collecting html2text==2020.1.16
[19:40:06.641]   Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
[19:40:06.719] Collecting pyyaml==6.0
[19:40:06.723]   Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
[19:40:06.736]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 kB 68.3 MB/s eta 0:00:00
[19:40:07.052] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[19:40:07.511] Collecting importlib-metadata>=4.4
[19:40:07.515]   Downloading importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
[19:40:07.600] Collecting zipp>=0.5
[19:40:07.604]   Downloading zipp-3.8.1-py3-none-any.whl (5.6 kB)
[19:40:07.670] Using legacy 'setup.py install' for djongo, since package 'wheel' is not installed.
[19:40:07.670] Using legacy 'setup.py install' for tcping, since package 'wheel' is not installed.
[19:40:07.671] Using legacy 'setup.py install' for Unipath, since package 'wheel' is not installed.
[19:40:07.892] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, dj-database-url, certifi, boto, zipp, wrapt, whitenoise, urllib3, ujson, toml, soupsieve, six, rsa, pyyaml, pymongo, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, html2text, gunicorn, dnspython, colorama, click, charset-normalizer, asgiref, tcping, requests, python-dateutil, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, PyNaCl, Markdown, djongo, django-cors-headers, botocore, s3transfer, PyGithub, boto3
[19:40:07.946]   Running setup.py install for Unipath: started
[19:40:08.161]   Running setup.py install for Unipath: finished with status 'done'
[19:40:10.178]   Running setup.py install for tcping: started
[19:40:10.403]   Running setup.py install for tcping: finished with status 'done'
[19:40:12.468]   Running setup.py install for djongo: started
[19:40:12.746]   Running setup.py install for djongo: finished with status 'done'
[19:40:13.643] Successfully installed Deprecated-1.2.13 Django-3.0.5 Markdown-3.3.6 PyGithub-1.55 PyJWT-2.3.0 PyNaCl-1.4.0 Unipath-1.1 asgiref-3.4.1 autopep8-1.5.7 beautifulsoup4-4.10.0 boto-2.49.0 boto3-1.20.23 botocore-1.23.23 certifi-2021.5.30 cffi-1.15.0 charset-normalizer-2.0.4 click-8.0.1 colorama-0.4.4 dj-database-url-0.5.0 django-cors-headers-3.10.1 djongo-1.3.6 dnspython-1.16.0 gunicorn-20.1.0 html2text-2020.1.16 idna-3.2 importlib-metadata-4.12.0 jmespath-0.10.0 prettytable-2.2.0 pyasn1-0.4.8 pycodestyle-2.7.0 pycparser-2.21 pymongo-3.12.0 python-dateutil-2.8.2 python-decouple-3.4 pytz-2021.1 pyyaml-6.0 requests-2.27.1 rsa-4.7.2 s3transfer-0.5.0 six-1.16.0 soupsieve-2.2.1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 ujson-4.1.0 urllib3-1.26.7 wcwidth-0.2.5 whitenoise-5.3.0 wrapt-1.13.3 zipp-3.8.1
[19:40:13.643] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[19:40:13.727] 
[19:40:13.727] [notice] A new release of pip available: 22.1.2 -> 22.2.2
[19:40:13.727] [notice] To update, run: pip install --upgrade pip
[19:40:14.031] Traceback (most recent call last):
[19:40:14.031]   File "/vercel/path0/manage.py", line 22, in <module>
[19:40:14.031]     main()
[19:40:14.031]   File "/vercel/path0/manage.py", line 18, in main
[19:40:14.031]     execute_from_command_line(sys.argv)
[19:40:14.031]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:40:14.031]     utility.execute()
[19:40:14.032]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[19:40:14.032]     settings.INSTALLED_APPS
[19:40:14.032]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[19:40:14.032]     self._setup(name)
[19:40:14.032]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[19:40:14.032]     self._wrapped = Settings(settings_module)
[19:40:14.032]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[19:40:14.032]     mod = importlib.import_module(self.SETTINGS_MODULE)
[19:40:14.032]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:40:14.032]     return _bootstrap._gcd_import(name[level:], package, level)
[19:40:14.032]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:40:14.032]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:40:14.032]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:40:14.032]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:40:14.033]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:40:14.033]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:40:14.033]   File "/vercel/path0/core/settings.py", line 25, in <module>
[19:40:14.033]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[19:40:14.033]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[19:40:14.033]     raise KeyError(key) from None
[19:40:14.033] KeyError: 'DOMAINS'
[19:40:14.107] Traceback (most recent call last):
[19:40:14.107]   File "/vercel/path0/manage.py", line 22, in <module>
[19:40:14.107]     main()
[19:40:14.107]   File "/vercel/path0/manage.py", line 18, in main
[19:40:14.107]     execute_from_command_line(sys.argv)
[19:40:14.107]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[19:40:14.107]     utility.execute()
[19:40:14.108]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
[19:40:14.108]     settings.INSTALLED_APPS
[19:40:14.108]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
[19:40:14.108]     self._setup(name)
[19:40:14.108]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
[19:40:14.108]     self._wrapped = Settings(settings_module)
[19:40:14.108]   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
[19:40:14.108]     mod = importlib.import_module(self.SETTINGS_MODULE)
[19:40:14.108]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[19:40:14.108]     return _bootstrap._gcd_import(name[level:], package, level)
[19:40:14.108]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[19:40:14.108]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[19:40:14.108]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[19:40:14.108]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[19:40:14.108]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[19:40:14.108]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[19:40:14.108]   File "/vercel/path0/core/settings.py", line 25, in <module>
[19:40:14.108]     ALLOWED_HOSTS = json.loads(os.environ["DOMAINS"])
[19:40:14.108]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[19:40:14.109]     raise KeyError(key) from None
[19:40:14.118] Error! Command "./migrate.sh" exited with 1


### 复现链接

_No response_

### 截图

![image](https://user-images.githubusercontent.com/8143207/183288944-f62504db-08fa-4848-a740-17455e77cffe.png)

**Comment by am-abudu** [comment]
#159
