### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by sysfox** [Qexo/Qexo#250]
### Qexo 版本

v2.1.5

### 问题描述

Vercel报错
`
[10:55:09.684] Retrieving list of deployment files...
[10:55:12.850] Downloading 95 deployment files...
[10:55:14.219] Restored build cache
[10:55:14.256] Running "vercel build"
[10:55:14.759] Vercel CLI 28.5.6
[10:55:14.887] WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[10:55:15.806] Collecting asgiref==3.5.2
[10:55:15.824]   Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
[10:55:15.861] Collecting autopep8==2.0.0
[10:55:15.866]   Downloading autopep8-2.0.0-py2.py3-none-any.whl (45 kB)
[10:55:15.872]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 11.0 MB/s eta 0:00:00
[10:55:15.906] Collecting beautifulsoup4==4.11.1
[10:55:15.911]   Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
[10:55:15.918]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 27.7 MB/s eta 0:00:00
[10:55:15.959] Collecting boto==2.49.0
[10:55:15.977]   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
[10:55:15.995]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 87.4 MB/s eta 0:00:00
[10:55:16.478] Collecting boto3==1.26.13
[10:55:16.490]   Downloading boto3-1.26.13-py3-none-any.whl (132 kB)
[10:55:16.498]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.5/132.5 kB 26.7 MB/s eta 0:00:00
[10:55:17.100] Collecting botocore==1.29.13
[10:55:17.107]   Downloading botocore-1.29.13-py3-none-any.whl (9.9 MB)
[10:55:17.197]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 113.6 MB/s eta 0:00:00
[10:55:17.274] Collecting certifi==2022.9.24
[10:55:17.278]   Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
[10:55:17.286]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 31.1 MB/s eta 0:00:00
[10:55:17.490] Collecting cffi==1.15.1
[10:55:17.495]   Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
[10:55:17.506]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.2/441.2 kB 53.3 MB/s eta 0:00:00
[10:55:17.602] Collecting charset-normalizer==2.1.1
[10:55:17.606]   Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
[10:55:17.652] Collecting click==8.1.3
[10:55:17.657]   Downloading click-8.1.3-py3-none-any.whl (96 kB)
[10:55:17.664]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 20.6 MB/s eta 0:00:00
[10:55:17.701] Collecting colorama==0.4.6
[10:55:17.705]   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
[10:55:17.743] Collecting Deprecated==1.2.13
[10:55:17.748]   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[10:55:17.777] Collecting dj-database-url==1.0.0
[10:55:17.782]   Downloading dj_database_url-1.0.0-py3-none-any.whl (6.6 kB)
[10:55:17.907] Collecting Django==3.2.16
[10:55:17.911]   Downloading Django-3.2.16-py3-none-any.whl (7.9 MB)
[10:55:17.986]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 110.2 MB/s eta 0:00:00
[10:55:18.069] Collecting djongo==1.3.6
[10:55:18.093]   Downloading djongo-1.3.6.tar.gz (331 kB)
[10:55:18.103]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.6/331.6 kB 47.2 MB/s eta 0:00:00
[10:55:18.127]   Preparing metadata (setup.py): started
[10:55:18.307]   Preparing metadata (setup.py): finished with status 'done'
[10:55:18.354] Collecting django-cors-headers==3.13.0
[10:55:18.360]   Downloading django_cors_headers-3.13.0-py3-none-any.whl (13 kB)
[10:55:18.401] Collecting dnspython==2.2.1
[10:55:18.406]   Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
[10:55:18.415]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 40.8 MB/s eta 0:00:00
[10:55:18.454] Collecting gunicorn==20.1.0
[10:55:18.458]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[10:55:18.465]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 17.9 MB/s eta 0:00:00
[10:55:18.495] Collecting idna==3.4
[10:55:18.499]   Downloading idna-3.4-py3-none-any.whl (61 kB)
[10:55:18.505]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 12.8 MB/s eta 0:00:00
[10:55:18.534] Collecting jmespath==1.0.1
[10:55:18.538]   Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
[10:55:18.574] Collecting prettytable==3.5.0
[10:55:18.579]   Downloading prettytable-3.5.0-py3-none-any.whl (26 kB)
[10:55:18.632] Collecting pyasn1==0.4.8
[10:55:18.636]   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[10:55:18.643]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 17.1 MB/s eta 0:00:00
[10:55:18.673] Collecting pycodestyle==2.9.1
[10:55:18.678]   Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
[10:55:18.686]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB 6.2 MB/s eta 0:00:00
[10:55:18.720] Collecting pycparser==2.21
[10:55:18.725]   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
[10:55:18.731]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 25.9 MB/s eta 0:00:00
[10:55:18.771] Collecting PyGithub==1.57
[10:55:18.778]   Downloading PyGithub-1.57-py3-none-any.whl (297 kB)
[10:55:18.788]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.6/297.6 kB 43.2 MB/s eta 0:00:00
[10:55:18.827] Collecting PyJWT==2.6.0
[10:55:18.831]   Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
[10:55:19.283] Collecting pymongo==4.3.3
[10:55:19.290]   Downloading pymongo-4.3.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (492 kB)
[10:55:19.300]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.1/492.1 kB 60.1 MB/s eta 0:00:00
[10:55:19.350] Collecting PyNaCl==1.5.0
[10:55:19.357]   Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
[10:55:19.371]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 77.8 MB/s eta 0:00:00
[10:55:19.408] Collecting python-dateutil==2.8.2
[10:55:19.423]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[10:55:19.432]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 41.3 MB/s eta 0:00:00
[10:55:19.459] Collecting python-decouple==3.6
[10:55:19.464]   Downloading python_decouple-3.6-py3-none-any.whl (9.9 kB)
[10:55:19.544] Collecting pytz==2022.6
[10:55:19.556]   Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
[10:55:19.567]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 kB 57.2 MB/s eta 0:00:00
[10:55:19.671] Collecting requests==2.28.1
[10:55:19.676]   Downloading requests-2.28.1-py3-none-any.whl (62 kB)
[10:55:19.682]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.9 MB/s eta 0:00:00
[10:55:19.735] Collecting rsa==4.9
[10:55:19.739]   Downloading rsa-4.9-py3-none-any.whl (34 kB)
[10:55:19.775] Collecting s3transfer==0.6.0
[10:55:19.780]   Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
[10:55:19.787]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 17.3 MB/s eta 0:00:00
[10:55:19.819] Collecting six==1.16.0
[10:55:19.823]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[10:55:19.863] Collecting soupsieve==2.3.2.post1
[10:55:19.868]   Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
[10:55:19.900] Collecting sqlparse==0.2.4
[10:55:19.905]   Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
[10:55:19.933] Collecting tcping==0.1.1rc1
[10:55:19.939]   Downloading tcping-0.1.1rc1.tar.gz (4.1 kB)
[10:55:19.945]   Preparing metadata (setup.py): started
[10:55:20.120]   Preparing metadata (setup.py): finished with status 'done'
[10:55:20.149] Collecting toml==0.10.2
[10:55:20.154]   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
[10:55:20.264] Collecting ujson==5.5.0
[10:55:20.269]   Downloading ujson-5.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46 kB)
[10:55:20.275]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 11.1 MB/s eta 0:00:00
[10:55:20.310] Collecting Unipath==1.1
[10:55:20.316]   Downloading Unipath-1.1.tar.gz (30 kB)
[10:55:20.326]   Preparing metadata (setup.py): started
[10:55:20.496]   Preparing metadata (setup.py): finished with status 'done'
[10:55:20.557] Collecting urllib3==1.26.12
[10:55:20.562]   Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
[10:55:20.569]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 28.6 MB/s eta 0:00:00
[10:55:20.597] Collecting wcwidth==0.2.5
[10:55:20.601]   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
[10:55:20.641] Collecting whitenoise==6.2.0
[10:55:20.646]   Downloading whitenoise-6.2.0-py3-none-any.whl (19 kB)
[10:55:20.771] Collecting wrapt==1.14.1
[10:55:20.777]   Downloading wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
[10:55:20.784]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 15.4 MB/s eta 0:00:00
[10:55:20.823] Collecting Markdown==3.4.1
[10:55:20.835]   Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
[10:55:20.841]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 22.8 MB/s eta 0:00:00
[10:55:20.870] Collecting html2text==2020.1.16
[10:55:20.875]   Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
[10:55:20.947] Collecting pyyaml==6.0
[10:55:20.960]   Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
[10:55:20.973]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 kB 68.4 MB/s eta 0:00:00
[10:55:21.020] Collecting python-gitlab==3.11.0
[10:55:21.024]   Downloading python_gitlab-3.11.0-py3-none-any.whl (128 kB)
[10:55:21.032]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.6/128.6 kB 25.5 MB/s eta 0:00:00
[10:55:21.077] Collecting tomli
[10:55:21.081]   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
[10:55:21.431] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 18)) (58.1.0)
[10:55:21.912] Collecting importlib-metadata>=4.4
[10:55:21.917]   Downloading importlib_metadata-5.1.0-py3-none-any.whl (21 kB)
[10:55:21.977] Collecting requests-toolbelt>=0.9.1
[10:55:21.981]   Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
[10:55:21.989]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 8.5 MB/s eta 0:00:00
[10:55:22.078] Collecting zipp>=0.5
[10:55:22.085]   Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
[10:55:22.432] Installing collected packages: wcwidth, Unipath, sqlparse, pytz, python-decouple, pyasn1, boto, zipp, wrapt, whitenoise, urllib3, ujson, tomli, toml, soupsieve, six, rsa, pyyaml, PyJWT, pycparser, pycodestyle, prettytable, jmespath, idna, html2text, gunicorn, dnspython, colorama, click, charset-normalizer, certifi, asgiref, tcping, requests, python-dateutil, pymongo, importlib-metadata, Django, Deprecated, cffi, beautifulsoup4, autopep8, requests-toolbelt, PyNaCl, Markdown, djongo, django-cors-headers, dj-database-url, botocore, s3transfer, python-gitlab, PyGithub, boto3
[10:55:22.481]   DEPRECATION: Unipath is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
[10:55:22.482]   Running setup.py install for Unipath: started
[10:55:22.702]   Running setup.py install for Unipath: finished with status 'done'
[10:55:24.552]   DEPRECATION: tcping is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
[10:55:24.553]   Running setup.py install for tcping: started
[10:55:24.767]   Running setup.py install for tcping: finished with status 'done'
[10:55:27.112]   DEPRECATION: djongo is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
[10:55:27.113]   Running setup.py install for djongo: started
[10:55:27.384]   Running setup.py install for djongo: finished with status 'done'
[10:55:28.527] Successfully installed Deprecated-1.2.13 Django-3.2.16 Markdown-3.4.1 PyGithub-1.57 PyJWT-2.6.0 PyNaCl-1.5.0 Unipath-1.1 asgiref-3.5.2 autopep8-2.0.0 beautifulsoup4-4.11.1 boto-2.49.0 boto3-1.26.13 botocore-1.29.13 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 click-8.1.3 colorama-0.4.6 dj-database-url-1.0.0 django-cors-headers-3.13.0 djongo-1.3.6 dnspython-2.2.1 gunicorn-20.1.0 html2text-2020.1.16 idna-3.4 importlib-metadata-5.1.0 jmespath-1.0.1 prettytable-3.5.0 pyasn1-0.4.8 pycodestyle-2.9.1 pycparser-2.21 pymongo-4.3.3 python-dateutil-2.8.2 python-decouple-3.6 python-gitlab-3.11.0 pytz-2022.6 pyyaml-6.0 requests-2.28.1 requests-toolbelt-0.10.1 rsa-4.9 s3transfer-0.6.0 six-1.16.0 soupsieve-2.3.2.post1 sqlparse-0.2.4 tcping-0.1.1rc1 toml-0.10.2 tomli-2.0.1 ujson-5.5.0 urllib3-1.26.12 wcwidth-0.2.5 whitenoise-6.2.0 wrapt-1.14.1 zipp-3.11.0
[10:55:28.528] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[10:55:28.951] 获取本地配置文件失败, 使用环境变量进行初始化
[10:55:28.951] 获取本地配置文件失败, 使用环境变量进行初始化
[10:55:29.757]            _               _ 
[10:55:29.757]      /\   | |             | |
[10:55:29.757]     /  \  | |__  _   _  __| |_   _ 
[10:55:29.757]    / /\ \ | |_ \| | | |/ _| | | | |
[10:55:29.757]   / ____ \| |_) | |_| | (_| | |_| |
[10:55:29.757]  /_/    \_\____/ \____|\____|\____|
[10:55:29.758] 当前环境: Vercel
[10:55:29.836] Migrations for 'hexoweb':
[10:55:29.836]   hexoweb/migrations/0001_initial.py
[10:55:29.836]     - Create model Cache
[10:55:29.836]     - Create model CustomModel
[10:55:29.836]     - Create model FriendModel
[10:55:29.836]     - Create model ImageModel
[10:55:29.836]     - Create model NotificationModel
[10:55:29.836]     - Create model SettingModel
[10:55:29.837]     - Create model StatisticPV
[10:55:29.837]     - Create model StatisticUV
[10:55:29.837]     - Create model TalkModel
[10:55:29.838] Traceback (most recent call last):
[10:55:29.838]   File "/vercel/path1/manage.py", line 22, in <module>
[10:55:29.838]     main()
[10:55:29.838]   File "/vercel/path1/manage.py", line 18, in main
[10:55:29.838]     execute_from_command_line(sys.argv)
[10:55:29.838]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
[10:55:29.839]     utility.execute()
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
[10:55:29.839]     self.fetch_command(subcommand).run_from_argv(self.argv)
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
[10:55:29.839]     connections.close_all()
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 213, in close_all
[10:55:29.839]     connection.close()
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
[10:55:29.839]     return func(*args, **kwargs)
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 294, in close
[10:55:29.839]     self._close()
[10:55:29.839]   File "/usr/local/lib/python3.9/site-packages/djongo/base.py", line 208, in _close
[10:55:29.840]     if self.connection:
[10:55:29.840]   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1161, in __bool__
[10:55:29.840]     raise NotImplementedError(
[10:55:29.840] NotImplementedError: Database objects do not implement truth value testing or bool(). Please compare with None instead: database is not None
[10:55:30.279] 获取本地配置文件失败, 使用环境变量进行初始化
[10:55:30.279] 获取本地配置文件失败, 使用环境变量进行初始化
[10:55:31.044]            _               _ 
[10:55:31.044]      /\   | |             | |
[10:55:31.044]     /  \  | |__  _   _  __| |_   _ 
[10:55:31.044]    / /\ \ | |_ \| | | |/ _| | | | |
[10:55:31.044]   / ____ \| |_) | |_| | (_| | |_| |
[10:55:31.044]  /_/    \_\____/ \____|\____|\____|
[10:55:31.044] 当前环境: Vercel
[10:55:31.125] Operations to perform:
[10:55:31.125]   Apply all migrations: auth, contenttypes, hexoweb, sessions
[10:55:31.134] Running migrations:
[10:55:31.135]   No migrations to apply.
[10:55:31.599] Traceback (most recent call last):
[10:55:31.599]   File "/vercel/path1/manage.py", line 22, in <module>
[10:55:31.599]     main()
[10:55:31.599]   File "/vercel/path1/manage.py", line 18, in main
[10:55:31.599]     execute_from_command_line(sys.argv)
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
[10:55:31.599]     utility.execute()
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
[10:55:31.599]     self.fetch_command(subcommand).run_from_argv(self.argv)
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
[10:55:31.599]     connections.close_all()
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 213, in close_all
[10:55:31.599]     connection.close()
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
[10:55:31.599]     return func(*args, **kwargs)
[10:55:31.599]   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 294, in close
[10:55:31.600]     self._close()
[10:55:31.600]   File "/usr/local/lib/python3.9/site-packages/djongo/base.py", line 208, in _close
[10:55:31.600]     if self.connection:
[10:55:31.600]   File "/usr/local/lib/python3.9/site-packages/pymongo/database.py", line 1161, in __bool__
[10:55:31.600]     raise NotImplementedError(
[10:55:31.600] NotImplementedError: Database objects do not implement truth value testing or bool(). Please compare with None instead: database is not None
[10:55:31.972] Error: Command "./migrate.sh" exited with 1`

### 截图

None

**Comment by am-abudu** [comment]
请尝试更新dev分支

**Comment by sysfox** [comment]
问题已解决
