### ISSUE TITLE
3.1.1版本提示500

### ISSUE THREAD

**Issue by leioukupo** [Qexo/Qexo#503]
### Qexo 版本

3.0.0

### 平台

本地部署

### 问题描述

从3.0.0升级到3.1.1，提示500
更新没问题，更新后刷新就提示错误500

### 复现链接

本地部署的，没有域名

### 截图

![image](https://github.com/Qexo/Qexo/assets/60430874/50836823-da10-47e8-884d-a55b21d0e635)

**Comment by am-abudu** [comment]
需要提供控制台报错信息

**Comment by leioukupo** [comment]
/usr/bin/python3 -u manage.py runserver 0.0.0.0:8000 --noreload
获取本地配置文件成功, 使用本地数据库配置
Performing system checks...

           _               _
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
 /_/    \_\____/ \____|\____|\____|
当前环境: 本地
System check identified no issues (0 silenced).
February 16, 2024 - 21:35:31
Django version 3.2.20, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[16/Feb/2024 21:35:35] INFO: OK: /(log.py.log_response[line:224])
Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/leioukupo/.Qexo/hexoweb/views.py", line 406, in index
    for i in _images:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")
[16/Feb/2024 21:35:35] "GET / HTTP/1.1" 200 14257
[16/Feb/2024 21:35:35] INFO: 保存设置LAST_LOGIN => 1708090535(functions.py.save_setting[line:259])
[16/Feb/2024 21:35:35] ERROR: 页面不存在: TemplateDoesNotExist('home/favicon.ico')(views.py.pages[line:838])
[16/Feb/2024 21:35:35] "GET /favicon.ico HTTP/1.1" 200 14405
[16/Feb/2024 21:35:37] INFO: 获取更新成功: 3.1.1(functions.py.get_latest_version[line:290])
[16/Feb/2024 21:35:37] "GET /api/get_notifications/?csrfmiddlewaretoken=FZGTfB8wFpBrkyNNn4eKtOFjc1WN2hCvCK0yq13Enc0c0YXomv1SWiVOOZYFTABJ HTTP/1.1" 200 28
[16/Feb/2024 21:35:41] INFO: OK: /(log.py.log_response[line:224])
Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/leioukupo/.Qexo/hexoweb/views.py", line 406, in index
    for i in _images:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")
[16/Feb/2024 21:35:41] "GET / HTTP/1.1" 200 14257
[16/Feb/2024 21:35:41] INFO: 保存设置LAST_LOGIN => 1708090541(functions.py.save_setting[line:259])
[16/Feb/2024 21:35:41] ERROR: 页面不存在: TemplateDoesNotExist('home/favicon.ico')(views.py.pages[line:838])
[16/Feb/2024 21:35:41] "GET /favicon.ico HTTP/1.1" 200 14405
[16/Feb/2024 21:35:43] INFO: 获取更新成功: 3.1.1(functions.py.get_latest_version[line:290])
[16/Feb/2024 21:35:43] "GET /api/get_notifications/?csrfmiddlewaretoken=4U0aGvHubyxd4BgvOV3S5AbVJngImnJO1FkPRVCCTlWYK1q6NmQ0y4rqlliAdGI2 HTTP/1.1" 200 28

**Comment by leioukupo** [comment]
> 需要提供控制台报错信息
/usr/bin/python3 -u manage.py runserver 0.0.0.0:8000 --noreload
获取本地配置文件成功, 使用本地数据库配置
Performing system checks...

           _               _
     /\   | |             | |
    /  \  | |__  _   _  __| |_   _
   / /\ \ | |_ \| | | |/ _| | | | |
  / ____ \| |_) | |_| | (_| | |_| |
 /_/    \_\____/ \____|\____|\____|
当前环境: 本地
System check identified no issues (0 silenced).
February 16, 2024 - 21:35:31
Django version 3.2.20, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[16/Feb/2024 21:35:35] INFO: OK: /(log.py.log_response[line:224])
Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/leioukupo/.Qexo/hexoweb/views.py", line 406, in index
    for i in _images:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")
[16/Feb/2024 21:35:35] "GET / HTTP/1.1" 200 14257
[16/Feb/2024 21:35:35] INFO: 保存设置LAST_LOGIN => 1708090535(functions.py.save_setting[line:259])
[16/Feb/2024 21:35:35] ERROR: 页面不存在: TemplateDoesNotExist('home/favicon.ico')(views.py.pages[line:838])
[16/Feb/2024 21:35:35] "GET /favicon.ico HTTP/1.1" 200 14405
[16/Feb/2024 21:35:37] INFO: 获取更新成功: 3.1.1(functions.py.get_latest_version[line:290])
[16/Feb/2024 21:35:37] "GET /api/get_notifications/?csrfmiddlewaretoken=FZGTfB8wFpBrkyNNn4eKtOFjc1WN2hCvCK0yq13Enc0c0YXomv1SWiVOOZYFTABJ HTTP/1.1" 200 28
[16/Feb/2024 21:35:41] INFO: OK: /(log.py.log_response[line:224])
Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/leioukupo/.Qexo/hexoweb/views.py", line 406, in index
    for i in _images:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/leioukupo/.local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")
[16/Feb/2024 21:35:41] "GET / HTTP/1.1" 200 14257
[16/Feb/2024 21:35:41] INFO: 保存设置LAST_LOGIN => 1708090541(functions.py.save_setting[line:259])
[16/Feb/2024 21:35:41] ERROR: 页面不存在: TemplateDoesNotExist('home/favicon.ico')(views.py.pages[line:838])
[16/Feb/2024 21:35:41] "GET /favicon.ico HTTP/1.1" 200 14405
[16/Feb/2024 21:35:43] INFO: 获取更新成功: 3.1.1(functions.py.get_latest_version[line:290])
[16/Feb/2024 21:35:43] "GET /api/get_notifications/?csrfmiddlewaretoken=4U0aGvHubyxd4BgvOV3S5AbVJngImnJO1FkPRVCCTlWYK1q6NmQ0y4rqlliAdGI2 HTTP/1.1" 200 28

**Comment by am-abudu** [comment]
可以提供部署的日志吗？理论上，数据库会在部署时同步

**Comment by leioukupo** [comment]
> 可以提供部署的日志吗？理论上，数据库会在部署时同步

怎么提供？？我的数据库是docker起的

**Comment by am-abudu** [comment]
我了解了，请你进到容器内，执行命令
python3 manage.py makemigrations
python3 manage.py migrate
并检查问题是否解决。如果没有，请发给我执行结果

**Comment by leioukupo** [comment]
> 我了解了，请你进到容器内，执行命令 python3 manage.py makemigrations python3 manage.py migrate 并检查问题是否解决。如果没有，请发给我执行结果

谢谢！已经正常了

**Comment by am-abudu** [comment]
可以告诉我你使用的Docker部署方案吗，我需要更正错误

**Comment by leioukupo** [comment]
> 可以告诉我你使用的Docker部署方案吗，我需要更正错误

1panel里建的mysqsl数据库，
config.py
```python
import pymysql
pymysql.install_as_MySQLdb()
DOMAINS = ["127.0.0.1","192.168.31.61","10.42.0.1"]
DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'qexo',
            'USER': 'qexo',
            'PASSWORD': 'xxxxxxx',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"
            }
    }
}
```
其他安装部署文档操作的，我自己设置了一个service管理qexo
qexo.service
```yml
[Unit]
Description=qexo  #qexo程序
After = network.target
[Service]
ExecStart=/usr/bin/python3 -u manage.py runserver 0.0.0.0:8000 --noreload
WorkingDirectory=/home/leioukupo/.Qexo
StandardOutput = inherit
StandardError = inherit
Restart = always
User=leioukupo
[Install]
WantedBy=multi-user.target
```

**Comment by HuoChaiSAMA** [comment]
同样的问题，查看上述控制台报错日志怀疑是这行出问题:
`pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")`
1054报错
在CSDN找到[这篇文章](https://blog.csdn.net/sodalife/article/details/83279438)，怀疑是在`pymysql`某步操作时未加引号
目前靠个人能力没有在可见的`.py`文件中找到import了pymysql库的，无法进一步确认错误代码位置，先补个issue

**Comment by am-abudu** [comment]
> 同样的问题，查看上述控制台报错日志怀疑是这行出问题: `pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")` 1054报错 在CSDN找到[这篇文章](https://blog.csdn.net/sodalife/article/details/83279438)，怀疑是在`pymysql`某步操作时未加引号 目前靠个人能力没有在可见的`.py`文件中找到import了pymysql库的，无法进一步确认错误代码位置，先补个issue

仅仅只是因为没有同步数据库造成的，如果是Vercel部署的话会自动更新数据库信息，本地部署更新如果用的是设置中的一键更新应当会自动同步。如果出现问题只要参考前面的方案手动同步即可

**Comment by HuoChaiSAMA** [comment]
> > 同样的问题，查看上述控制台报错日志怀疑是这行出问题: `pymysql.err.OperationalError: (1054, "Unknown column 'hexoweb_imagemodel.deleteConfig' in 'field list'")` 1054报错 在CSDN找到[这篇文章](https://blog.csdn.net/sodalife/article/details/83279438)，怀疑是在`pymysql`某步操作时未加引号 目前靠个人能力没有在可见的`.py`文件中找到import了pymysql库的，无法进一步确认错误代码位置，先补个issue
> 
> 仅仅只是因为没有同步数据库造成的，如果是Vercel部署的话会自动更新数据库信息，本地部署更新如果用的是设置中的一键更新应当会自动同步。如果出现问题只要参考前面的方案手动同步即可

同步未成功，重装了MySQL，没问题了。
计算机的尽头是重启hhh
