### ISSUE TITLE
一键更新到3.5.1后报错500 Internel Server error

### ISSUE THREAD

**Issue by ekyfig** [Qexo/Qexo#603]
### Qexo 版本

v3.5.1

### 平台

Vercel Neon PostgresDB

### 问题描述

在vercel上部署的QEXO使用一键更新后报错，runtime log如下：
_bootstrap._gcd_import(name[level:], package, level)
File "/var/task/django/db/backends/postgresql/base.py", line 29, in <module>
raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
使用环境变量中的PostgreSQL数据库
Traceback (most recent call last):
File "/var/task/django/db/backends/postgresql/base.py", line 25, in <module>
import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "./core/wsgi.py", line 16, in <module>
app = application = get_wsgi_application()
File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/var/task/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/var/task/django/apps/registry.py", line 114, in populate
app_config.import_models()
File "/var/task/django/apps/config.py", line 301, in import_models
self.models_module = import_module(models_module_name)
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/var/task/django/contrib/auth/models.py", line 3, in <module>
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
File "/var/task/django/contrib/auth/base_user.py", line 48, in <module>
class AbstractBaseUser(models.Model):
File "/var/task/django/db/models/base.py", line 122, in __new__
new_class.add_to_class('_meta', Options(meta, app_label))
File "/var/task/django/db/models/base.py", line 326, in add_to_class
value.contribute_to_class(cls, name)
File "/var/task/django/db/models/options.py", line 207, in contribute_to_class
self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
File "/var/task/django/utils/connection.py", line 15, in __getattr__
return getattr(self._connections[self._alias], item)
File "/var/task/django/utils/connection.py", line 62, in __getitem__
conn = self.create_connection(alias)
File "/var/task/django/db/utils.py", line 204, in create_connection
backend = load_backend(db['ENGINE'])
File "/var/task/django/db/utils.py", line 111, in load_backend
return import_module('%s.base' % backend_name)
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/var/task/django/db/backends/postgresql/base.py", line 29, in <module>
raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
使用环境变量中的PostgreSQL数据库
Traceback (most recent call last):
File "/var/task/django/db/backends/postgresql/base.py", line 25, in <module>
import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "./core/wsgi.py", line 16, in <module>
app = application = get_wsgi_application()
File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/var/task/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/var/task/django/apps/registry.py", line 114, in populate
app_config.import_models()
File "/var/task/django/apps/config.py", line 301, in import_models
self.models_module = import_module(models_module_name)
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/var/task/django/contrib/auth/models.py", line 3, in <module>
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
File "/var/task/django/contrib/auth/base_user.py", line 48, in <module>
class AbstractBaseUser(models.Model):
File "/var/task/django/db/models/base.py", line 122, in __new__
new_class.add_to_class('_meta', Options(meta, app_label))
File "/var/task/django/db/models/base.py", line 326, in add_to_class
value.contribute_to_class(cls, name)
File "/var/task/django/db/models/options.py", line 207, in contribute_to_class
self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
File "/var/task/django/utils/connection.py", line 15, in __getattr__
return getattr(self._connections[self._alias], item)
File "/var/task/django/utils/connection.py", line 62, in __getitem__
conn = self.create_connection(alias)
File "/var/task/django/db/utils.py", line 204, in create_connection
backend = load_backend(db['ENGINE'])
File "/var/task/django/db/utils.py", line 111, in load_backend
return import_module('%s.base' % backend_name)
File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/var/task/django/db/backends/postgresql/base.py", line 29, in <module>
raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
Python process exited with exit status: 1. The logs above can help with debugging the issue.

### 截图

![屏幕截图 2024-12-26 180536](https://github.com/user-attachments/assets/20749487-9e7d-46b2-909f-12e21cd87137)

**Comment by kandyhe** [comment]
同样的问题。

**Comment by am-abudu** [comment]
抱歉，我好像处理依赖问题时漏了一个依赖。我将马上推一个修复。

**Comment by am-abudu** [comment]
我已经推送了更新 6ab66a621e50731de0d4e47679ba26c2e352d7c9

请更新到3.5.2版本并检查是否可以正常运行

**Comment by ShanMuYunQiu** [comment]
我更新到了3.5.2貌似还是不行？先前在3.5.0版本可以正常运行，更新到3.5.2目前Vercel的Logs日志如下，在网页F12也没有报错，但还是如上所述出现了Error 500
![image](https://github.com/user-attachments/assets/23301d7d-ec6d-43a8-b47e-c81f595da0f7)
![image](https://github.com/user-attachments/assets/431aaf25-12a9-4247-ab3f-9fd293b2479f)

另外请问Vercel有没有办法回退到先前的部署，查了好久没有找到QAQ，如下图3.5.0的部署在第四行，Rollback只能最近的一个部署，Promote不可用，也没法Redeploy（有更新的部署无法redeploy）
![image](https://github.com/user-attachments/assets/94667ad5-8665-496a-a1ee-be447d072b3b)

**Comment by am-abudu** [comment]
@ShanMuYunQiu 请更新到Dev分支，我修复了对MongoDB的支持。但MongoDB的支持器存在一些弊端，我建议尽快更换到其他平台

**Comment by ShanMuYunQiu** [comment]
感谢，更新后问题已解决，将更换至其他平台

**Comment by ShanMuYunQiu** [comment]
不过好像其他平台的也不行，我按照文档完全重新部署了Qexo，使用了Vercel的Neon Postgres，仍然出现了Error 500，日志如下
![image](https://github.com/user-attachments/assets/e33d771d-4795-496b-9ef7-85620414f86b)
![image](https://github.com/user-attachments/assets/3e3e3606-ea33-4310-9da0-eabb2c673940)
![image](https://github.com/user-attachments/assets/f011bead-c597-4f10-a8c6-4d1528427cf4)

此外 PostgreSQL/SupaBase 貌似现在也是直接在Vercel创建了，我通过Vercel创建连接后，也是Error 500
![image](https://github.com/user-attachments/assets/aa30e3cd-eba8-4922-ad5c-58aa32cc2755)
![image](https://github.com/user-attachments/assets/9d91c3d8-4f05-4830-86a8-3ec15629a9c0)

**Comment by am-abudu** [comment]
@ShanMuYunQiu 我的migrate命令没有被正确执行，我怀疑是Vercel又偷偷改了什么东西。请给我一段时间排查

**Comment by am-abudu** [comment]
现在请使用3.5.3版本

**Comment by ShanMuYunQiu** [comment]
谢谢，已成功部署
